videoid: 0
caps:
  -
    videoid: 0
    prefix: "[1]left"
  -
    videoid: 2
    prefix: "[1]right"

port: "/dev/ttyACM0"
#port: "/dev/ttyUSB0"
baudrate: 9600
detecturl: "http://192.168.1.107:8000/photo"
#detecturl: "http://127.0.0.1:8000/photo"
pi2url: "http://192.168.1.101:8000/photo"
machineid: "demo"
password: "123456"
doorpin: 16
